[loadbalancer]
lb ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/vagrant_keys/lb_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers]
web1 ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/vagrant_keys/web1_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
web2 ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/vagrant_keys/web2_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
web3 ansible_host=192.168.56.13 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/vagrant_keys/web3_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[monitor]
noc_monitor ansible_host=192.168.56.20 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/vagrant_keys/monitor_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all_nodes:children]
loadbalancer
webservers
monitor
