Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "lb" do |lb|
    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip: "192.168.56.10"
  end

  (1..3).each do |i|
    config.vm.define "web#{i}" do |web|
      web.vm.hostname = "web#{i}"
      web.vm.network "private_network", ip: "192.168.56.1#{i}"
    end
  end

  # NEW: Provision the NOC Monitoring Server
  config.vm.define "monitor" do |mon|
    mon.vm.hostname = "noc-monitor"
    mon.vm.network "private_network", ip: "192.168.56.20"
    mon.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # Grafana needs a bit more RAM
    end
  end
end